In [2]:
import sqlite3
import pandas as pd

In [3]:
ratings = pd.read_csv("../data/ml-100k/u.data", sep = "\t", header=None, names=['user_id', 'item_id', 'rating', 'timestamp'])
users = pd.read_csv("../data/ml-100k/u.user", sep="|", header=None, names=['user_id', 'age', 'gender', 'occupation', 'zip'])
movies = pd.read_csv("../data/ml-100k/u.item", sep="|", header=None, encoding="latin-1", usecols=[0, 1, 2], names=["item_id", "title", "release_date"])

In [4]:
conn = sqlite3.connect('../data/movielens.db')

ratings.to_sql('ratings', conn, if_exists='replace', index=False)
users.to_sql('users', conn, if_exists='replace', index=False)
movies.to_sql('movies', conn, if_exists='replace', index=False)

pd.read_sql_query("SELECT COUNT(*) AS n FROM ratings", conn)

        n
0  100000

In [5]:
pd.read_sql_query("SELECT COUNT(*) AS n, COUNT(DISTINCT item_id) AS cnt_movies, COUNT(DISTINCT user_id) AS cnt_users FROM ratings", conn)

        n  cnt_movies  cnt_users
0  100000        1682        943

In [6]:
pd.read_sql_query("""SELECT ratings.item_id, movies.title, COUNT(*) AS num_rat
FROM ratings
JOIN movies ON ratings.item_id = movies.item_id
GROUP BY ratings.item_id, movies.title
ORDER BY num_rat DESC
LIMIT 10""", conn)

   item_id                          title  num_rat
0       50               Star Wars (1977)      583
1      258                 Contact (1997)      509
2      100                   Fargo (1996)      508
3      181      Return of the Jedi (1983)      507
4      294               Liar Liar (1997)      485
5      286    English Patient, The (1996)      481
6      288                  Scream (1996)      478
7        1               Toy Story (1995)      452
8      300           Air Force One (1997)      431
9      121  Independence Day (ID4) (1996)      429

In [7]:
pd.read_sql_query("""SELECT user_id, COUNT(*) AS num_ratings
FROM ratings
GROUP BY user_id
ORDER BY num_ratings DESC
LIMIT 10""", conn)

   user_id  num_ratings
0      405          737
1      655          685
2       13          636
3      450          540
4      276          518
5      416          493
6      537          490
7      303          484
8      234          480
9      393          448

In [8]:
pd.read_sql_query("""SELECT user_id, COUNT(*) AS num_ratings
FROM ratings
GROUP BY user_id
ORDER BY num_ratings DESC
LIMIT 10""", conn)

   user_id  num_ratings
0      405          737
1      655          685
2       13          636
3      450          540
4      276          518
5      416          493
6      537          490
7      303          484
8      234          480
9      393          448

In [ ]:
pd.read_sql_query("""SELECT user_id, item_id, rating
FROM ratings
JOIN movies ON movies.item_id=ratings.item_id
JOIN users ON users.user_id=ratings.user_id
GROUP BY user_id
ORDER BY num_ratings DESC
LIMIT 10""", conn)